version: '3'

services:
  step-ca:
    container_name: step-ca
    image: smallstep/step-ca
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /tank/docker/step-ca:/home/step
