services:
  step-ca:
    container_name: step-ca
    image: smallstep/step-ca
    restart: unless-stopped
    ports:
      - 9000:9000
    user: "993"
    volumes:
      - /containers/step-ca:/home/step
