version: '3'

services:
  step-ca:
    container_name: step-ca
    image: smallstep/step-ca
    restart: unless-stopped
    network_mode: host
    ports:
      - 9000:9000
    labels:
      traefik.enable: true
      traefik.http.services.step-ca.loadbalancer.server.port: 9000
      traefik.http.services.step-ca.loadbalancer.server.scheme: https
      traefik.http.routers.step-ca.rule: Host(`ca`) || Host(`ca.home.joe.nyland.io`)
    volumes:
      - /containers/step-ca:/home/step
